**Dataset Title:** Population Variance of Thermoflexus hugenholtzii in Great Boiling Spring

**Dataset Curator:** Gillyan Valencia, MS graduate student, José R. de la Torre lab, Department of Biology, San Francisco State University (SFSU)

**Dataset version:** 1.2, 4.24.25

**Dataset citation and DOI:** Data statement author: Gillyan Valencia, MS graduate student, de la Torre Lab, Department of Biology, San Francisco State University

**Data statement citation:** authors, date, title, version, institution, and URL or DOI.

### Languages
English

## Datset Summary
This dataset contains frequences of single nucleotide variant (SNV) and single codon variant (SCV) data for selected core genes (rpoB, gyrB, recA) across multiple environmental samples. Each variant record includes positional information, associated gene annotations, allele or codon frequencies, and contextual data such as sampling site, month, and temperature. This dataset provides a resource for exploring microbial population structure, genetic diversity, and evolutionary pressures across spatial and temporal gradients.

## Data Collection:

**Field Sampling:** 
Data was collected from field sampling of the terrestrial hot spring Great Boiling Spring in Gerlach, Nevada, United States. Sediment was collected from the top 1 cm profile of each sample site into a sterile plastic beaker. The sediment was homogenized and alloquoted in 5 mL increments into 50 mL sterile falcon tubes. The samples were stored on dry ice until transportation back to the laboratory where they were kept at -80 C until DNA extraction. DNA was extracted from samples and short-read sequencing was obtained through illumina sequencing. 

**Bioinformatics:** Raw reads were obtained of the forward and reverse strand for each of the 5 sample points through illumina sequencing. The raw reads were assembled using SPAdes followed by binning with MetaBat2. Using Anvio v8, gene annotations were performed based on the Clusters of Orthologous Groups (COG) database. Functional annotations were used to extract sequences matching genes of interest, including DNA polymerase III alpha, RNA polymerase subunit beta, and DNA gyrase subunit B, for downstream comparative and evolutionary analyses.

## Curation Rational:

This dataset was created to analyze variation in SNPs and SCVs in the thermophilic bacteria Thermoflexus Hugenholtzii of 3 commonly studied core genes rpoB- the beta subunit of RNA polymerase in bacteria, gyrB- the beta subunit of DNA gyrase, and recA- a key protein involved in the homologous DNA repair process. 

```{r}
# Datasets
snp <- read.csv("Thermo_Hugo_SNP.csv")
scv <- read.csv("Thermo_Hugo_SCV.csv")
head(scv)
head(snp)
```

## Discussion of Biases

Sampling locations in this study were limited and may not capture the full microbial diversity present in the spring. Thermoflexus hugenholtzii was selected for analysis due to its high abundance and consistent presence across all sample sites. The metagenome-assembled genome (MAG) for T. hugenholtzii was derived from the June Site B sample, as it had the highest completeness and lowest contamination among all MAGs generated by MetaBAT2. This MAG was subsequently used as the reference genome for comparative analyses across all sample sites.

## Personal and Sensitive Information
There is no personal or sensitive information included in these data.













